### ISSUE TITLE
Ошибка в значении  VOICE_DIRECTOR

### ISSUE THREAD

**Issue by Penguinnie** [LinFor/jellyfin-plugin-kinopoisk#23]
Не удается обновить метаданные некоторых фильмов/сериалов. В логах однотипные ошибки. Ругается на значения DESIGN, OPERATOR, VOICE_DIRECTOR.

[2024-05-16 22:52:00.493 +00:00] [INF] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Anime/Mononoke-hime 1997 kp441.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-16 22:52:01.329 +00:00] [ERR] [3] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "КиноПоиск"
System.Runtime.CompilerServices.SwitchExpressionException: Non-exhaustive switch expression failed to match its input.
Unmatched value was VOICE_DIRECTOR.
   at <PrivateImplementationDetails>.ThrowSwitchExpressionException(Object unmatchedValue)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonType(StaffResponseProfessionKey src)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfo(StaffResponse src)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfos(ICollection`1 src)
   at Jellyfin.Plugin.Kinopoisk.MetadataProviders.BaseVideoMetadataProvider`2.GetMetadata(TLookupInfoType info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by nordeep** [comment]
Могли бы, пожалуйста, выпустить релиз с данным исправлением?

**Comment by entei-11** [comment]
Есть временный обход проблемы, пока обновленный manifest.json НЕ слит в master.

Можно добавить новый репозиторий в Jellyfin, используя исправленный манифест https://raw.githubusercontent.com/LinFor/jellyfin-plugin-kinopoisk/40dff87914142bcac295bb29c1a4765655f11adb/dist/manifest.json. На всякий случай этот репозиторий я назвал "Кинопоиск 10.9.0.1 [NOT RELEASED BUGIX]", чтобы не забыть его потом удалить.

После этого у Кинопоиска появилась доступна новая версия 10.9.0.1 с исправлением.

Затем в моем случае пришлось удалить плагин Кинопоиск и установить его заново, чтобы подхватилась исправленная версия.

![image](https://github.com/user-attachments/assets/b9d3a786-1fa4-4359-8323-fea2448d100e)
![image](https://github.com/user-attachments/assets/5fba8235-55c6-4287-a0ff-935c314ba9a4)

**Comment by popov-aa** [comment]
@entei-11 эту проблему лечит, но добавляет другую: `Requested value 'YANDEX_DISK' was not found.`
