### ISSUE TITLE
Error in "КиноПоиск"

### ISSUE THREAD

**Issue by mirlex1986** [LinFor/jellyfin-plugin-kinopoisk#26]
> HTTP Response: 
> 
> 
> 
> KinopoiskUnofficialInfo.ApiClient.ApiException: Could not deserialize the response body stream as KinopoiskUnofficialInfo.ApiClient.VideoResponse.
> 
> Status: 200
> Response: 
> 
>  ---> Newtonsoft.Json.JsonSerializationException: Error converting value "YANDEX_DISK" to type 'KinopoiskUnofficialInfo.ApiClient.VideoResponse_itemsSite'. Path 'items[2].site', line 1, position 276.
>  ---> System.ArgumentException: Requested value 'YANDEX_DISK' was not found.
>    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

**Comment by urtaevS** [comment]
Так и не работает поиск метаданных.

**Comment by mirlex1986** [comment]
@skrashevich, тэгаю как было сказано в другом ишью

**Comment by GdalexAlex** [comment]
Добрый день! 
Тоже не обновляются метаданные. Есть два сервера в разных сетях. На одном все работает (Версия jellyfin: 10.8.10, КиноПоиск: 10.7.5.4), на другом (Версия jellyfin: 10.9.1, КиноПоиск: 10.9.0.0) подтягиваются только картинки. Никакой более информации не обновляется.
Лог:
[2024-06-13 11:53:28.026 +03:00] [INF] [30] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item efe77d24-0896-670c-21da-06f5fbba747b-"Анна": [("kinopoisk": "1049727")]
[2024-06-13 11:53:28.030 +03:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Фильмы/Архив_фильмов/Анна.2019.BDRip.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-06-13 11:53:28.287 +03:00] [ERR] [30] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "КиноПоиск"
System.Runtime.CompilerServices.SwitchExpressionException: Non-exhaustive switch expression failed to match its input.
Unmatched value was VOICE_DIRECTOR.
   at <PrivateImplementationDetails>.ThrowSwitchExpressionException(Object unmatchedValue)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonType(StaffResponseProfessionKey src)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfo(StaffResponse src)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfos(ICollection`1 src)
   at Jellyfin.Plugin.Kinopoisk.MetadataProviders.BaseVideoMetadataProvider`2.GetMetadata(TLookupInfoType info, CancellationToken cancellationToken)

   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by NickCoolberg** [comment]
Встретился с той же проблемой на КиноПоиск: 10.9 и КиноПоиск: 10.8.*

Пока что временным решением стал откат на КиноПоиск: 10.7.5.4

**Comment by GdalexAlex** [comment]
![Image](https://github.com/user-attachments/assets/1c20d724-5abd-493d-b46b-62f518de41d0)
