### ISSUE TITLE
Error: Unmatched value was OPERATOR

### ISSUE THREAD

**Issue by AndrewNeborsky** [LinFor/jellyfin-plugin-kinopoisk#30]
```
2024-05-31 23:57:37.249 +03:00] [INF] [50] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/Media/TV Shows/Travelers (2016)/Season 03/Travelers (2016) - S03E07 - Trevor [WEBRip-1080p][AC3 5.1][XviD].avi\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-31 23:57:37.543 +03:00] [ERR] [50] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "КиноПоиск"
System.Runtime.CompilerServices.SwitchExpressionException: Non-exhaustive switch expression failed to match its input.
Unmatched value was OPERATOR.
   at <PrivateImplementationDetails>.ThrowSwitchExpressionException(Object unmatchedValue)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonType(StaffResponseProfessionKey src)
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfo(StaffResponse src)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Jellyfin.Plugin.Kinopoisk.ApiModelExtensions.ToPersonInfos(ICollection`1 src)
   at Jellyfin.Plugin.Kinopoisk.MetadataProviders.BaseVideoMetadataProvider`2.GetMetadata(TLookupInfoType info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2024-05-31 23:57:37.717 +03:00] [WRN] [48] MediaBrowser.XbmcMetadata.Providers.SeriesNfoProvider: Trailer URL uses a deprecated format : "plugin://plugin.video.youtube/?action=play_video&videoid=2UpYmwGkbdc". Using "plugin://plugin.video.youtube/play/?video_id=2UpYmwGkbdc" instead is advised.
```
Версия сервера: linuxserver/jellyfin:10.9.2

**Comment by AndrewNeborsky** [comment]
Оказалось дубликат
