### ISSUE TITLE
No info from kinopoisk, used personal api key, plugin ver 10.9

### ISSUE THREAD

**Issue by ydrob** [LinFor/jellyfin-plugin-kinopoisk#35]
[2024-08-15 10:35:29.201 +03:00] [ERR] [71] KinopoiskUnofficialInfo.ApiClient.KinopoiskApiClient: Received non-success result status code 429 from Kinopoisk API, response content is:
{"message":"Rate limit exceeded"}
[2024-08-15 10:35:29.201 +03:00] [ERR] [71] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "КиноПоиск"
HTTP Response:

{"message":"Rate limit exceeded"}

KinopoiskUnofficialInfo.ApiClient.ApiException: Слишком много запросов. Лимит 10 запросов в секунду

Status: 429
Response:
{"message":"Rate limit exceeded"}
at KinopoiskUnofficialInfo.ApiClient.Client.StaffAllAsync(Int32 filmId, CancellationToken cancellationToken)
at KinopoiskUnofficialInfo.ApiClient.KinopoiskApiClient.Invoke[T](Func2 method, Nullable1 ct, String memberName)
at KinopoiskUnofficialInfo.ApiClient.CachedKinopoiskApiClient.<>c__DisplayClass11_01.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func2 factory)
at Jellyfin.Plugin.Kinopoisk.MetadataProviders.BaseVideoMetadataProvider2.GetMetadata(TLookupInfoType info, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService2.ExecuteRemoteProviders(MetadataResult1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable1 providers, CancellationToken cancellationToken)
[2024-08-15 10:35:29.222 +03:00] [ERR] [158] KinopoiskUnofficialInfo.ApiClient.KinopoiskApiClient: Received non-success result status code 429 from Kinopoisk API, response content is:
{"message":"Rate limit exceeded"}
[2024-08-15 10:35:29.222 +03:00] [ERR] [158] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "КиноПоиск"
HTTP Response:

{"message":"Rate limit exceeded"}

KinopoiskUnofficialInfo.ApiClient.ApiException: Слишком много запросов. Лимит 10 запросов в секунду

Status: 429
Response:
{"message":"Rate limit exceeded"}
at KinopoiskUnofficialInfo.ApiClient.Client.StaffAllAsync(Int32 filmId, CancellationToken cancellationToken)
at KinopoiskUnofficialInfo.ApiClient.KinopoiskApiClient.Invoke[T](Func2 method, Nullable1 ct, String memberName)
at KinopoiskUnofficialInfo.ApiClient.CachedKinopoiskApiClient.<>c__DisplayClass11_01.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func2 factory)
at Jellyfin.Plugin.Kinopoisk.MetadataProviders.BaseVideoMetadataProvider2.GetMetadata(TLookupInfoType info, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService2.ExecuteRemoteProviders(MetadataResult1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable1 providers, CancellationToken cancellationToken)
[2024-08-15 10:35:29.231 +03:00] [ERR] [28] KinopoiskUnofficialInfo.ApiClient.KinopoiskApiClient: Received non-success result status code 429 from Kinopoisk API, response content is:
{"message":"Rate limit exceeded"}
[2024-08-15 10:35:29.231 +03:00] [ERR] [28] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "КиноПоиск"
HTTP Response:

{"message":"Rate limit exceeded"}

**Comment by deadcxap** [comment]
Судя по "Rate limit exceeded" - у вас просто закончились бесплатные запросы API. Или подключать платный доступ, или удалять плагин - когда медиатека достаточно большая, то регулярное обновление метаданных просто не способно в выдаваемый бесплатный лимит влезть.

**Comment by ydrob** [comment]
Вот отсюда все работает с тем же personal api key
https://github.com/ydrob/jellyfin-plugin-kinopoisk

**Comment by KimIV** [comment]
> Вот отсюда все работает с тем же personal api key https://github.com/ydrob/jellyfin-plugin-kinopoisk

Подтверждаю! Работает!!!

**Comment by deadcxap** [comment]
А в чём разница, если из всех правок в том форке только версии в манифесте и имя автора изменены?

**Comment by LinFor** [comment]
Это ответ чужого api-сервиса, нечего править в плагине
