### ISSUE TITLE
Couldn't parse ISO 8601 date string '2021-04-06 18:12:00' Сразу после установки плагина ошибка

### ISSUE THREAD

**Issue by vervolk** [LinFor/jellyfin-plugin-kinopoisk#37]
Error
Couldn't parse ISO 8601 date string '2021-04-06 18:12:00'

Error: Couldn't parse ISO 8601 date string '2021-04-06 18:12:00'
    at o (http://192.168.88.8:8096/web/main.jellyfin.bundle.js?f1238435f421c71ad785:2:301722)
    at http://192.168.88.8:8096/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9626
    at Array.map (<anonymous>)
    at en (http://192.168.88.8:8096/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9435)
    at hu (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:60311)
    at xi (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:119252)
    at bs (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108504)
    at vs (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108432)
    at gs (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108295)
    at as (http://192.168.88.8:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:105130)

**Comment by ivspbitec** [comment]
Ошибка в датах https://raw.githubusercontent.com/LinFor/jellyfin-plugin-kinopoisk/master/dist/manifest.json 
Ошибка связана с неправильным форматом даты в строке ISO 8601. Ваша дата '2021-04-06 18:12:00' содержит пробел между датой и временем, что недопустимо в стандартном формате ISO 8601.
Чтобы исправить это, вам нужно заменить пробел на символ "T". Правильный формат должен выглядеть так:
'2021-04-06T18:12:00'

Я удалил версии из манифеста и исправил дату 

https://raw.githubusercontent.com/ivspbitec/jellyfin-plugin-kinopoisk/refs/heads/master/dist/manifest.json

**Comment by SlavaAndreevich** [comment]
Для версии 10.10 нужно ещё и номер версии в манифесте изменить, тогда всё работает

**Comment by LinFor** [comment]
Поправил старые записи в манифесте
